spring:
  datasource:        # JDBC Configuration
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/market
    username: postgres
    password: 123
  jpa:               # JPA Configuration
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:              # JSP File Configuration
    view:
      prefix: /views/
      suffix: .jsp