spring:
#  main:
#    web-application-type: none
  datasource:        # JDBC Configuration
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/market
    username: postgres
    password: 123
  jpa:               # JPA Configuration
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:              # JSP File Configuration
    view:
      prefix: /views/
      suffix: .jsp
server:
  port: 8282